version: 0.0
os: linux
files:
  - source: /FlaskApp
            /scripts/flask-server.service
    destination: /FlaskApp
                 /etc/systemd/system
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/remove_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root