version: 0.1
os: linux
files:
  - source: /FlaskApp/
    destination: /usr/local/bin/flask
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: /usr/local/bin/flask run --host=0.0.0.0 --port=80
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

