version: 0.0
os: linux
files:
  - source: /FlaskApp
    destination: /FlaskApp
# hooks:
#    ApplicationStart:
#     - location: /usr/local/bin/flask run --host=0.0.0.0 --port=80
#       timeout: 300
#       runas: root


